# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 499247a1c084555e0a4a27c71ce4e4fb9549e0a6d025fc305930ec05818aaf92650a7fea9405933d43919f9a223a852671a2683a71539deef35dd61e5b675232

test:
  secret_key_base: 633a9c2f1308a7871ba9ee1b7ab412979b15cb95776ed1f6c1fb8b8ebd808e820371c5e6adba8858de13d7737dc02c102e9aeeadf0d82c9b2f5ad27ff9c92661

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
